name: otlob_app
description: A Flutter-based mobile application for Egypt's authentic local food scene.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management - Latest stable with Riverpod 2.x
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  async: ^2.13.0

  # Networking - Latest stable with Dio and Retrofit
  dio: ^5.9.0
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.4

  # Navigation - Latest stable
  go_router: ^16.2.4
  app_links: ^6.4.1

  # Local Storage & Caching - Enhanced caching support
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_secure_storage: ^9.2.4
  dio_http_cache_lts: ^0.4.2

  # Location & Geolocation - Latest stable
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1

  # Maps Integration - Latest stable
  google_maps_flutter: ^2.9.0
  mapbox_maps_flutter: ^2.11.0
  flutter_map: ^7.0.2

  # Notifications - Latest stable
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^18.0.1
  awesome_notifications: ^0.10.0

  # Payments - Latest stable
  flutter_paymob: ^1.0.5
  flutter_inappwebview: ^6.1.5
  pay: ^2.0.0

  # Offline Support - Latest stable
  connectivity_plus: ^6.1.5
  flutter_offline: ^4.0.0
  cached_network_image: ^3.4.1

  # Firebase Services - Latest stable
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_analytics: ^12.0.2
  firebase_crashlytics: ^5.0.2
  google_sign_in: ^6.2.1

  # UI & Design - Latest stable
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10
  shimmer: ^3.0.0
  lottie: ^3.1.0
  google_fonts: ^6.2.0
  shadcn_ui: ^0.36.1
  styled_widget: ^0.4.1

  # Image & Media - Latest stable
  image_picker: ^1.2.0
  image_cropper: ^8.0.2
  photo_view: ^0.15.0

  # Internationalization - Latest stable
  easy_localization: ^3.0.7
  intl: ^0.20.2

  # Typeahead for autocomplete
  flutter_typeahead: ^5.2.0

  # RTL & Arabic Support
  flutter_localizations:
    sdk: flutter

  # Utilities - Latest stable
  logger: ^2.6.1
  uuid: ^4.5.1
  device_info_plus: ^12.1.0
  package_info_plus: ^8.1.1
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  get_it: ^8.0.2

  # PDF & Printing - Latest stable
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_pdfview: ^1.3.2

  # Icons
  cupertino_icons: ^1.0.6

  # Additional modern Flutter packages
  flutter_staggered_animations: ^1.1.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3
  timezone: any
  collection: any
  crypto: any
  http: any
dev_dependencies:
 flutter_test:
   sdk: flutter
 flutter_lints: ^6.0.0

 # Code Generation - Latest stable
 build_runner: ^2.4.13
 json_serializable: ^6.8.0
 retrofit_generator: ^9.7.0
 freezed: ^2.5.2
 riverpod_generator: ^2.6.1

 # Testing - Latest stable
 integration_test:
   sdk: flutter
 mockito: ^5.4.4
 test: ^1.25.8

 # Development Tools - Latest stable
 flutter_launcher_icons: ^0.14.2
 change_app_package_name: ^1.4.0




flutter:
  uses-material-design: true

  assets:
    - assets/fonts/tutano-cc/
    - assets/animations/
    - assets/translations/

  fonts:
    - family: TutanoCCV2
      fonts:
        - asset: assets/fonts/tutano-cc/tutano_cc_v2.ttf
    # Arabic Fonts for RTL Support - TODO: Add missing font files
    # - family: Cairo
    #   fonts:
    #     - asset: assets/fonts/cairo/Cairo-Regular.ttf
    #     - asset: assets/fonts/cairo/Cairo-Bold.ttf
    #       weight: 700
    # - family: NotoSansArabic
    #   fonts:
    #     - asset: assets/fonts/noto_sans_arabic/NotoSansArabic-Regular.ttf
    #     - asset: assets/fonts/noto_sans_arabic/NotoSansArabic-Bold.ttf
    #       weight: 700
