name: otlob_app
description: A premium Flutter-based mobile application for Egypt's authentic local food scene.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Networking
  retrofit: ^4.7.1
  dio: ^5.9.0
  json_annotation: ^4.9.0
  dio_http_cache_lts: ^0.4.2

  # Navigation
  go_router: ^16.2.4
  app_links: ^6.4.1

  # Local Storage
  shared_preferences: ^2.5.3
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_secure_storage: ^9.2.4

  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1

  # UI
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10
  shimmer: ^3.0.0
  image_picker: ^1.2.0

  # Internationalization
  easy_localization: ^3.0.7

  # Utilities
  logger: ^2.6.1
  intl: ^0.20.2
  uuid: ^4.5.1
  device_info_plus: ^12.1.0
  connectivity_plus: ^7.0.0

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2

  # Payment
  flutter_paymob: ^1.0.5
  flutter_inappwebview: ^6.1.5

  # Push Notifications
  firebase_messaging: ^16.0.2

  # Maps (UPDATED)
  google_maps_flutter: ^2.9.0

  # PDF Generation
  pdf: ^3.11.3
  printing: ^5.14.2

  # Google Fonts
  google_fonts: ^6.2.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.8.0
  json_serializable: ^6.11.1
  retrofit_generator: ^10.0.5
  drift_dev: ^2.28.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700