// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABY8EhUGSVqeyYyxp_KBuAVHMsmaezvPo',
    appId: '1:367665514133:web:7060479641f0229feebd9c',
    messagingSenderId: '367665514133',
    projectId: 'otlob-app-98371',
    authDomain: 'otlob-app-98371.firebaseapp.com',
    storageBucket: 'otlob-app-98371.firebasestorage.app',
    measurementId: 'G-72VXVLKEDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG-Rd6UvLBUTDTuYmc1s4A3NyAcYvrMJU',
    appId: '1:367665514133:android:c38bed0807b1ef94eebd9c',
    messagingSenderId: '367665514133',
    projectId: 'otlob-app-98371',
    storageBucket: 'otlob-app-98371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC94tGd4dz4KDfthv2CIVQ4pbHEB9aww-w',
    appId: '1:367665514133:ios:38e6da9303b865d5eebd9c',
    messagingSenderId: '367665514133',
    projectId: 'otlob-app-98371',
    storageBucket: 'otlob-app-98371.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABY8EhUGSVqeyYyxp_KBuAVHMsmaezvPo',
    appId: '1:367665514133:web:77ede10e97cbc9a6eebd9c',
    messagingSenderId: '367665514133',
    projectId: 'otlob-app-98371',
    authDomain: 'otlob-app-98371.firebaseapp.com',
    storageBucket: 'otlob-app-98371.firebasestorage.app',
    measurementId: 'G-TXEXWDX4Q3',
  );
}
