import "package:cloud_firestore/cloud_firestore.dart";
import "../../../features/home/domain/entities/restaurant.dart";

class FirebaseDataSeeder {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  Future<void> seedRestaurants() async {
    var restaurants = [
      const Restaurant(
        id: "1",
        name: "Mama's Kitchen",
        rating: 4.8,
        imageUrl:
            "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400",
        tawseyaCount: 25,
        cuisine: "Egyptian",
        description:
            "Authentic home-cooked Egyptian meals with fresh ingredients.",
        menuCategories: ["Mains", "Sides", "Desserts"],
        isOpen: true,
        distance: 1.2,
        address: "Downtown Cairo",
        priceLevel: 2,
        latitude: 30.0444,
        longitude: 31.2357,
        isFavorite: false,
      ),
      const Restaurant(
        id: "2",
        name: "Street Food Haven",
        rating: 4.6,
        imageUrl:
            "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400",
        tawseyaCount: 18,
        cuisine: "Street Food",
        description: "Vibrant street eats from local vendors.",
        menuCategories: ["Snacks", "Drinks"],
        isOpen: true,
        distance: 0.8,
        address: "Khan el-Khalili",
        priceLevel: 1,
        latitude: 30.0478,
        longitude: 31.2620,
        isFavorite: false,
      ),
      const Restaurant(
        id: "3",
        name: "Local Spice House",
        rating: 4.9,
        imageUrl:
            "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400",
        tawseyaCount: 32,
        cuisine: "Indian",
        description: "Spicy curries and aromatic biryanis.",
        menuCategories: ["Curries", "Breads", "Rice"],
        isOpen: true,
        distance: 2.5,
        address: "Maadi",
        priceLevel: 2.5,
        latitude: 29.9598,
        longitude: 31.2728,
        isFavorite: false,
      ),
      const Restaurant(
        id: "4",
        name: "Grandma's Bakery",
        rating: 4.7,
        imageUrl:
            "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400",
        tawseyaCount: 22,
        cuisine: "Bakery",
        description: "Freshly baked breads and pastries daily.",
        menuCategories: ["Breads", "Pastries", "Cakes"],
        isOpen: true,
        distance: 1.5,
        address: "Zamalek",
        priceLevel: 1.5,
        latitude: 30.0630,
        longitude: 31.2197,
        isFavorite: false,
      ),
      const Restaurant(
        id: "5",
        name: "River Side Grill",
        rating: 4.5,
        imageUrl:
            "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400",
        tawseyaCount: 15,
        cuisine: "Grill",
        description: "Grilled meats with Nile views.",
        menuCategories: ["Meats", "Seafood", "Salads"],
        isOpen: true,
        distance: 3,
        address: "Corniche",
        priceLevel: 3,
        latitude: 30.0444,
        longitude: 31.2357,
        isFavorite: false,
      ),
      const Restaurant(
        id: "6",
        name: "El Tabei El Domyati",
        rating: 4.4,
        imageUrl:
            "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400",
        tawseyaCount: 40,
        cuisine: "Egyptian",
        description: "Classic Egyptian koshary and ful medames.",
        menuCategories: ["Koshary", "Ful", "Snacks"],
        isOpen: true,
        distance: 2.1,
        address: "Dokki",
        priceLevel: 1,
        isFavorite: false,
      ),
      const Restaurant(
        id: "7",
        name: "Cairo Cafe",
        rating: 4.3,
        imageUrl:
            "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?w=400",
        tawseyaCount: 12,
        cuisine: "Cafe",
        description: "Relaxed cafe with shisha and Egyptian tea.",
        menuCategories: ["Drinks", "Snacks", "Desserts"],
        isOpen: true,
        distance: 0.7,
        address: "Garden City",
        priceLevel: 1.5,
        isFavorite: false,
      ),
      const Restaurant(
        id: "8",
        name: "Mediterraneo",
        rating: 4.7,
        imageUrl:
            "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?w=400",
        tawseyaCount: 28,
        cuisine: "Mediterranean",
        description: "Fresh seafood and mezze by the Nile.",
        menuCategories: ["Seafood", "Mezze", "Salads"],
        isOpen: true,
        distance: 3.2,
        address: "Giza",
        priceLevel: 3,
        isFavorite: false,
      ),
      const Restaurant(
        id: "9",
        name: "Felfela",
        rating: 4.2,
        imageUrl:
            "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?w=400",
        tawseyaCount: 35,
        cuisine: "Egyptian",
        description: "Iconic Egyptian restaurant with a wide menu.",
        menuCategories: ["Mains", "Salads", "Desserts"],
        isOpen: true,
        distance: 1.8,
        address: "Tahrir Square",
        priceLevel: 2,
        isFavorite: false,
      ),
      const Restaurant(
        id: "10",
        name: "Grill Master",
        rating: 4.6,
        imageUrl:
            "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?w=400",
        tawseyaCount: 20,
        cuisine: "Grill",
        description: "Premium grilled meats and kebabs.",
        menuCategories: ["Meats", "Kebabs", "Sides"],
        isOpen: true,
        distance: 2.9,
        address: "Heliopolis",
        priceLevel: 2.5,
        latitude: 31.2000,
        longitude: 29.9000,
        isFavorite: false,
      ),
      const Restaurant(
        id: "11",
        name: "Alexandria Fish Market",
        rating: 4.8,
        imageUrl:
            "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400",
        tawseyaCount: 30,
        cuisine: "Seafood",
        description: "Fresh fish and seafood, Alexandria style.",
        menuCategories: ["Fish", "Shrimp", "Rice"],
        isOpen: true,
        distance: 4.5,
        address: "Alexandria Corniche",
        priceLevel: 3.5,
        latitude: 30.0590,
        longitude: 31.3360,
        isFavorite: false,
      ),
      const Restaurant(
        id: "12",
        name: "Sultan Shawarma",
        rating: 4.5,
        imageUrl:
            "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400",
        tawseyaCount: 22,
        cuisine: "Middle Eastern",
        description: "Juicy shawarma and falafel wraps.",
        menuCategories: ["Shawarma", "Falafel", "Sides"],
        isOpen: true,
        distance: 1.1,
        address: "Nasr City",
        priceLevel: 1.5,
        latitude: 30.0630,
        longitude: 31.2197,
        isFavorite: false,
      ),
      const Restaurant(
        id: "13",
        name: "Le Pacha 1901",
        rating: 4.9,
        imageUrl:
            "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?w=400",
        tawseyaCount: 50,
        cuisine: "International",
        description: "Luxury dining on the Nile with global cuisine.",
        menuCategories: ["Mains", "Desserts", "Drinks"],
        isOpen: true,
        distance: 2,
        address: "Zamalek",
        priceLevel: 4,
        latitude: 30.0444,
        longitude: 31.2357,
        isFavorite: false,
      ),
      const Restaurant(
        id: "14",
        name: "El Abd Patisserie",
        rating: 4.7,
        imageUrl:
            "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400",
        tawseyaCount: 60,
        cuisine: "Bakery",
        description: "Famous for oriental sweets and cakes.",
        menuCategories: ["Cakes", "Pastries", "Sweets"],
        isOpen: true,
        distance: 1.3,
        address: "Downtown Cairo",
        priceLevel: 1.5,
        latitude: 30.0444,
        longitude: 31.2357,
        isFavorite: false,
      ),
      const Restaurant(
        id: "15",
        name: "Koshary El Tahrir",
        rating: 4.6,
        imageUrl:
            "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?w=400",
        tawseyaCount: 55,
        cuisine: "Egyptian",
        description: "Best koshary in town, quick and tasty.",
        menuCategories: ["Koshary", "Snacks", "Drinks"],
        isOpen: true,
        distance: 0.9,
        address: "Tahrir Square",
        priceLevel: 1,
        latitude: 30.0444,
        longitude: 31.2357,
        isFavorite: false,
      ),
      const Restaurant(
        id: "16",
        name: "Nile View Lounge",
        rating: 4.4,
        imageUrl:
            "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400",
        tawseyaCount: 10,
        cuisine: "Cafe",
        description: "Chill lounge with Nile views and coffee.",
        menuCategories: ["Drinks", "Snacks", "Desserts"],
        isOpen: true,
        distance: 2.7,
        address: "Corniche",
        priceLevel: 2,
        latitude: 31.2000,
        longitude: 29.9000,
        isFavorite: false,
      ),
      const Restaurant(
        id: "17",
        name: "El Borg",
        rating: 4.5,
        imageUrl:
            "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400",
        tawseyaCount: 38,
        cuisine: "Seafood",
        description: "Seafood grill with a view.",
        menuCategories: ["Fish", "Grill", "Salads"],
        isOpen: true,
        distance: 3.8,
        address: "Alexandria",
        priceLevel: 3,
        latitude: 30.0630,
        longitude: 31.2197,
        isFavorite: false,
      ),
      const Restaurant(
        id: "18",
        name: "Maison Thomas",
        rating: 4.3,
        imageUrl:
            "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?w=400",
        tawseyaCount: 27,
        cuisine: "Italian",
        description: "Classic Italian pizzas and pastas.",
        menuCategories: ["Pizza", "Pasta", "Salads"],
        isOpen: true,
        distance: 1.6,
        address: "Zamalek",
        priceLevel: 2.5,
        latitude: 29.9598,
        longitude: 31.2728,
        isFavorite: false,
      ),
      const Restaurant(
        id: "19",
        name: "Zooba",
        rating: 4.4,
        imageUrl:
            "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400",
        tawseyaCount: 45,
        cuisine: "Egyptian",
        description: "Modern Egyptian street food.",
        menuCategories: ["Ful", "Taameya", "Snacks"],
        isOpen: true,
        distance: 1,
        address: "Maadi",
        priceLevel: 1.5,
        isFavorite: false,
      ),
      const Restaurant(
        id: "20",
        name: "Taboula",
        rating: 4.7,
        imageUrl:
            "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?w=400",
        tawseyaCount: 33,
        cuisine: "Lebanese",
        description: "Authentic Lebanese cuisine and mezze.",
        menuCategories: ["Mezze", "Grill", "Desserts"],
        isOpen: true,
        distance: 2.2,
        address: "Garden City",
        priceLevel: 2.5,
        isFavorite: false,
      ),
      const Restaurant(
        id: "21",
        name: "Abou El Sid",
        rating: 4.6,
        imageUrl:
            "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400",
        tawseyaCount: 36,
        cuisine: "Egyptian",
        description: "Traditional Egyptian dishes in a vintage setting.",
        menuCategories: ["Mains", "Appetizers", "Desserts"],
        isOpen: true,
        distance: 1.7,
        address: "Zamalek",
        priceLevel: 2.5,
        isFavorite: false,
      ),
      const Restaurant(
        id: "22",
        name: "Kazouza",
        rating: 4.2,
        imageUrl:
            "https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?w=400",
        tawseyaCount: 19,
        cuisine: "Cafe",
        description: "Retro Egyptian cafe with sandwiches and drinks.",
        menuCategories: ["Sandwiches", "Drinks", "Desserts"],
        isOpen: true,
        distance: 1.4,
        address: "Heliopolis",
        priceLevel: 1.5,
        isFavorite: false,
      ),
      const Restaurant(
        id: "23",
        name: "Gad",
        rating: 4.1,
        imageUrl:
            "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400",
        tawseyaCount: 50,
        cuisine: "Egyptian",
        description: "Popular chain for Egyptian fast food.",
        menuCategories: ["Sandwiches", "Mains", "Snacks"],
        isOpen: true,
        distance: 1.9,
        address: "Nasr City",
        priceLevel: 1,
        isFavorite: false,
      ),
      const Restaurant(
        id: "24",
        name: "Carlo's",
        rating: 4.5,
        imageUrl:
            "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400",
        tawseyaCount: 21,
        cuisine: "Mediterranean",
        description: "Trendy spot for Mediterranean fusion.",
        menuCategories: ["Mains", "Salads", "Desserts"],
        isOpen: true,
        distance: 2.4,
        address: "Zamalek",
        priceLevel: 2.5,
        isFavorite: false,
      ),
      const Restaurant(
        id: "25",
        name: "Om Hassan",
        rating: 4.3,
        imageUrl:
            "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?w=400",
        tawseyaCount: 29,
        cuisine: "Grill",
        description: "Family grill house with Egyptian classics.",
        menuCategories: ["Grill", "Mains", "Salads"],
        isOpen: true,
        distance: 2,
        address: "Giza",
        priceLevel: 2,
        isFavorite: false,
      ),
    ];

    var batch = _firestore.batch();

    for (var restaurant in restaurants) {
      var docRef = _firestore.collection("restaurants").doc(restaurant.id);
      batch.set(docRef, {
        ...restaurant.toJson(),
        "createdAt": FieldValue.serverTimestamp(),
        "updatedAt": FieldValue.serverTimestamp(),
        "searchKeywords": [
          restaurant.name.toLowerCase(),
          restaurant.cuisine.toLowerCase(),
          ...restaurant.menuCategories.map((cat) => cat.toLowerCase()),
          restaurant.address.toLowerCase(),
          ...restaurant.description.toLowerCase().split(" "),
        ],
      });
    }

    await batch.commit();
    print("Seeded ${restaurants.length} restaurants");
  }

  Future<void> seedSampleData() async {
    await seedRestaurants();
    print("Data seeding completed");
  }
}
